add ZeroCopy in transaction and block
falian-lawchain/DNA pull request #2
Opened 2018-12-05 09:45 UTC by lucas7788

add ZeroCopy in transaction and block

2018-12-05 10:07 UTC, laizy commented on common/uint160.go
> +	//log.Tracef("[AddressToProgramHash] address: %s", addr)
remove commented code

2018-12-05 10:10 UTC, laizy commented on core/asset/asset.go
> +	sink.WriteBytes([]byte{byte(a.RecordType)})
use `sink.WriteByte(a.Precision)`

2018-12-05 10:12 UTC, laizy commented on core/asset/asset.go
> +	t, _, irregular, eof := source.NextVarBytes()
test this function, it seems buggy.

2018-12-05 10:12 UTC, laizy commented on core/asset/asset.go
> +	name, _, irregular, eof := source.NextString()
check `irregular` here

2018-12-05 10:13 UTC, laizy commented on core/asset/config.json
> +{}
remove this file

2018-12-05 10:20 UTC, laizy requested changes

2018-12-05 10:20 UTC, laizy commented on core/code/FunctionCode.go
> +	paramType, _, irregular, eof := source.NextVarBytes()
check irregular here

2018-12-05 10:20 UTC, laizy commented on core/contract/program/Program.go
> +	data, _, irregular, eof = source.NextVarBytes()
check irregular

2018-12-05 10:20 UTC, laizy commented on core/ledger/block.go
> +		transaction.Serialization(sink)
handle error

2018-12-05 10:20 UTC, laizy commented on core/ledger/block.go
> +    if eof {
format code

2018-12-05 10:20 UTC, laizy commented on core/ledger/block.go
> +		transaction.Deserialization(source)
handle error

2018-12-05 10:20 UTC, laizy commented on crypto/crypto.go
> +	bufX := []byte{}
avoid duplicated code

2018-12-05 11:05 UTC, lucas7788 commented on common/uint160.go
> +	//log.Tracef("[AddressToProgramHash] address: %s", addr)
ok

2018-12-06 09:49 UTC, laizy requested changes

2018-12-06 09:49 UTC, laizy commented on core/asset/asset.go
> +    sink.WriteByte(byte(a.AssetType))
format code

2018-12-06 09:49 UTC, laizy commented on core/ledger/block.go
> +	b.Blockdata.Deserialization(source)
check error

2018-12-06 09:49 UTC, laizy commented on core/ledger/blockdata.go
> +	return nil
format code

2018-12-06 09:49 UTC, laizy commented on core/ledger/header.go
> +	sink.WriteByte(byte(0))
`0` is not equal `'0'`

2018-12-07 10:57 UTC, laizy approved these changes

2018-12-07 11:25 UTC, merged